/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bp2proje2merve;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.sql.*;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Merve
 */
public class OgretmenEkran extends javax.swing.JFrame {

    DefaultTableModel dtm = new DefaultTableModel();
    String cheader[] = {"Ogrenci No", "Ders", "Vize", "Quiz", "Labaratuar", "Final", "Ortalama"};
    DefaultComboBoxModel dcbm = new DefaultComboBoxModel();

    /**
     * Creates new form OgretmenEkran
     */
    public OgretmenEkran() throws SQLException {
        initComponents();
//        this.getContentPane().setBackground(Color.white);
        dtm.setColumnIdentifiers(cheader);
        jTable1.setModel(dtm);
        // Ogrenc, comboBox doldurma

        try {
            Connection conn = DriverManager.getConnection("jdbc:derby://localhost:1527/sample", "app", "app");
            Statement sta = conn.createStatement();
            String Sql = "select * from OGRENCI";
            ResultSet rs = sta.executeQuery(Sql);
            while (rs.next()) {
                dcbm.addElement(rs.getString("KULLANICI"));

            }
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(OgretmenEkran.class.getName()).log(Level.SEVERE, null, ex);
        }
        jComboBox1.setModel(dcbm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ders = new javax.swing.JComboBox<>();
        quiz = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lab = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        finall = new javax.swing.JTextField();
        ekle = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ort = new javax.swing.JTextField();
        degistir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        sil = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ortalama = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        vize = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Sorgula = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ders.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matematik", "Fizik", "Kimya", "Programlama" }));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Merve\\Desktop\\create_thumb.png")); // NOI18N

        jButton2.setText("Ana Ekrana Dön");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        ekle.setText("Ekle");
        ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekleActionPerformed(evt);
            }
        });

        jLabel2.setText("Öğrenci no:");

        degistir.setText("Değiştir");
        degistir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                degistirActionPerformed(evt);
            }
        });

        jLabel3.setText("Vize:");

        sil.setText("Sil");
        sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silActionPerformed(evt);
            }
        });

        jLabel4.setText("Quiz:");

        jLabel5.setText("Lab:");

        jLabel6.setText("Final:");

        jLabel7.setText("Ortalama:");

        ortalama.setText("Ortalama Hesapla");
        ortalama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ortalamaActionPerformed(evt);
            }
        });

        jLabel8.setText("Ders:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        Sorgula.setText("Sorgula");
        Sorgula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SorgulaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ders, 0, 142, Short.MAX_VALUE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(finall)
                                            .addComponent(lab, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(quiz, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(vize, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextField9, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField7, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(ort, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ekle, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(ortalama, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(degistir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(Sorgula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(ders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(vize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(quiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(finall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ortalama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ekle)
                    .addComponent(sil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(degistir)
                .addGap(0, 14, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(Sorgula)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Giris a = new Giris();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekleActionPerformed

        Connection conn = null;
        Statement sta = null;
        int ogrno = Integer.parseInt(jComboBox1.getSelectedItem().toString());
        String ders1 = String.valueOf(ders.getSelectedItem());
        int vize1 = Integer.parseInt(vize.getText());
        int quiz1 = Integer.parseInt(quiz.getText());
        int lab1 = Integer.parseInt(lab.getText());
        int finali = Integer.parseInt(finall.getText());
        double ortalamam = Double.parseDouble(ort.getText());
        try {
            File dosya = new File("C:\\Users\\Merve\\Desktop\\OgrenciNotları.txt");
            FileWriter yazici = new FileWriter(dosya, true);
            BufferedWriter yaz = new BufferedWriter(yazici);

            yaz.write(ogrno + "");
            yaz.write("       ");
            yaz.write(ders1);
            yaz.write("       ");
            yaz.write(vize1 + "");
            yaz.write("       ");
            yaz.write(quiz1 + "");
            yaz.write("       ");
            yaz.write(lab1 + "");
            yaz.write("       ");
            yaz.write(finali + "");
            yaz.write("       ");
            yaz.write(ortalamam + "");
            yaz.write("       ");
            System.out.print("\n\n");

            yaz.close();

        } catch (Exception hata) {
            hata.printStackTrace();
        }

        try {
            conn = DriverManager.getConnection("jdbc:derby://localhost:1527/sample", "app", "app");
            sta = conn.createStatement();
            String Sql = "select * from OGRNOT";
            ResultSet rs = sta.executeQuery(Sql);

            String sql2 = "INSERT INTO OGRNOT "
                    + " VALUES (" + ogrno + ",'" + ders1 + "'," + vize1 + "," + quiz1 + "," + lab1 + "," + finali + "," + ortalamam + ")";
            sta.executeUpdate(sql2);
            JOptionPane.showMessageDialog(rootPane, "Kayıt Başarılı", "Başarılı", 1);

        } catch (Exception e) {
        }

        vize.setText("");
        lab.setText("");
        finall.setText("");
        ort.setText("");
        quiz.setText("");

        ResetDtm();
        Goster();

    }//GEN-LAST:event_ekleActionPerformed

    private void ortalamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ortalamaActionPerformed
        // TODO add your handling code here:
        if (Double.parseDouble(vize.getText()) > 100 | Double.parseDouble(finall.getText()) > 100 | Double.parseDouble(quiz.getText()) > 100 | Double.parseDouble(lab.getText()) > 100) {
            JOptionPane.showMessageDialog(this, "100'den büyük bir sayı girdiniz. Lütfen düzeltin ", "Hata", 0);
        } else if ((Integer.parseInt(jTextField7.getText()) + Integer.parseInt(jTextField8.getText()) + Integer.parseInt(jTextField9.getText()) + Integer.parseInt(jTextField10.getText())) != 100) {
            JOptionPane.showMessageDialog(this, "Yüzde hesabını yanlış yaptınız ", "Hata!!!", 0);
        } else {
            double ort1 = (Double.parseDouble(finall.getText()) * Double.parseDouble(jTextField8.getText()) / 100) + (Double.parseDouble(vize.getText()) * Double.parseDouble(jTextField7.getText()) / 100) + (Double.parseDouble(quiz.getText()) * Double.parseDouble(jTextField9.getText()) / 100) + (Double.parseDouble(lab.getText()) * Double.parseDouble(jTextField10.getText()) / 100);
            ort.setText(String.valueOf(ort1));
        }

    }//GEN-LAST:event_ortalamaActionPerformed

    private void silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silActionPerformed
        int no = Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
        try {
            Connection conn = DriverManager.getConnection("jdbc:derby://localhost:1527/sample", "app", "app");
            Statement sta = conn.createStatement();
            String Sql = "select * from OGRNOT";
            ResultSet rs = sta.executeQuery(Sql);
            String sql2 = "DELETE FROM OGRNOT "
                    + "WHERE OGRENCINO=" + no + "";
            sta.executeUpdate(sql2);
            Goster();
        } catch (Exception e) {
        }
        ResetDtm();
        Goster();

    }//GEN-LAST:event_silActionPerformed

    private void SorgulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SorgulaActionPerformed
        // TODO add your handling code here:
        vize.setText("");
        lab.setText("");
        finall.setText("");
        ort.setText("");
        quiz.setText("");
        if (jComboBox1.getSelectedItem().toString() == null || jComboBox1.getSelectedItem().toString().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Bir öğrenci numarası girmelisiniz");
            return;
        }
        int gelenNo = Integer.parseInt(jComboBox1.getSelectedItem().toString());
        try {
            Connection conn = DriverManager.getConnection("jdbc:derby://localhost:1527/sample", "app", "app");
            Statement sta = conn.createStatement();
            ResultSet rs = sta.executeQuery("SELECT * FROM OGRNOT WHERE OGRENCINO=" + gelenNo);

            while (rs.next()) {

                int no = rs.getInt("OGRENCINO");

                String ders1 = rs.getString("DERS");
                ders.setSelectedItem(ders1 + "");
                int vize1 = rs.getInt("VIZE");
                vize.setText(vize1 + "");
                int quiz1 = rs.getInt("QUIZ");
                quiz.setText(quiz1 + "");
                int lab1 = rs.getInt("LAB");
                lab.setText(lab1 + "");
                int finall1 = rs.getInt("FINAL");
                finall.setText(finall1 + "");
                int ort1 = rs.getInt("ORTALAMA");
                ort.setText(ort1 + "");

            }
        } catch (SQLException e) {
            java.util.logging.Logger.getLogger(OgretmenEkran.class.getName()).log(Level.SEVERE, null, e);
        }

    }//GEN-LAST:event_SorgulaActionPerformed

    private void degistirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_degistirActionPerformed

        int gelenNo = Integer.parseInt(jComboBox1.getSelectedItem().toString());
        try {
            Connection conn = DriverManager.getConnection("jdbc:derby://localhost:1527/sample", "app", "app");
            Statement sta = conn.createStatement();
            ResultSet rs = sta.executeQuery("SELECT * FROM OGRNOT WHERE OGRENCINO=" + gelenNo);

            if (rs.next()) {

                String updateString = "UPDATE OGRNOT SET DERS ='" + ders.getSelectedItem()
                        + "',VIZE=" + vize.getText()
                        + ",QUIZ=" + quiz.getText()
                        + ",LAB=" + lab.getText()
                        + ",FINAL=" + finall.getText()
                        + ",ORTALAMA=" + ort.getText() + "WHERE OGRENCINO=" + jComboBox1.getSelectedItem().toString();
                System.out.println("" + updateString);
                sta.executeUpdate(updateString);
            }
        } catch (SQLException e) {
            java.util.logging.Logger.getLogger(OgretmenEkran.class.getName()).log(Level.SEVERE, null, e);
        }
        vize.setText("");
        lab.setText("");
        finall.setText("");
        ort.setText("");
        quiz.setText("");

        ResetDtm();
        Goster();

    }//GEN-LAST:event_degistirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OgretmenEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OgretmenEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OgretmenEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OgretmenEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new OgretmenEkran().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(OgretmenEkran.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Sorgula;
    private javax.swing.JButton degistir;
    private javax.swing.JComboBox<String> ders;
    private javax.swing.JButton ekle;
    private javax.swing.JTextField finall;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField lab;
    private javax.swing.JTextField ort;
    private javax.swing.JButton ortalama;
    private javax.swing.JTextField quiz;
    private javax.swing.JButton sil;
    private javax.swing.JTextField vize;
    // End of variables declaration//GEN-END:variables

    private void ResetDtm() {
        dtm = new DefaultTableModel();
        dtm.setColumnIdentifiers(cheader);
        jTable1.setModel(dtm);
    }

    private void Goster() {
        try {
            Connection conn = DriverManager.getConnection("jdbc:derby://localhost:1527/sample", "app", "app");
            Statement sta = conn.createStatement();
            String Sql = "select * from OGRNOT";
            ResultSet rs = sta.executeQuery(Sql);
            while (rs.next()) {

                dtm.addRow(new Object[]{rs.getInt("OGRENCINO") + "", rs.getString("DERS") + "", rs.getString("VIZE") + "", rs.getString("QUIZ") + "", rs.getString("LAB") + "", rs.getString("FINAL") + "", rs.getString("ORTALAMA") + ""});

            }
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(OgretmenEkran.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
